Repository owncloud/docs-ocis, pull requests merged in 2022-08, with the labels that each got.

#215 Update / Rewrite of the Kubernetes and Helm documentation
  antora.yml
  modules/ROOT/examples/deployment/container/orchestration/builtin-user-mgmt-secrets-tab-1.yaml
  modules/ROOT/examples/deployment/container/orchestration/builtin-user-mgmt-secrets-tab-2.yaml
  modules/ROOT/examples/deployment/container/orchestration/builtin-user-mgmt-secrets-tab-3.yaml
  modules/ROOT/examples/deployment/container/orchestration/email-notification-tab-1.yaml
  modules/ROOT/examples/deployment/container/orchestration/email-notification-tab-2.yaml
  modules/ROOT/examples/deployment/container/orchestration/email-notification-tab-3.yaml
  modules/ROOT/examples/deployment/container/orchestration/external-user-mgmt-secrets-tab-1.yaml
  modules/ROOT/examples/deployment/container/orchestration/external-user-mgmt-secrets-tab-2.yaml
  modules/ROOT/examples/deployment/container/orchestration/external-user-mgmt-secrets-tab-3.yaml
  modules/ROOT/examples/deployment/container/orchestration/nginx-ingress-tab-1.yaml
  modules/ROOT/examples/deployment/container/orchestration/nginx-ingress-tab-2.yaml
  modules/ROOT/examples/deployment/container/orchestration/nginx-ingress-tab-3.yaml
  modules/ROOT/examples/deployment/container/orchestration/secrets-tab-1.yaml
  modules/ROOT/examples/deployment/container/orchestration/secrets-tab-2.yaml
  modules/ROOT/examples/deployment/container/orchestration/secrets-tab-3.yaml
  modules/ROOT/examples/deployment/container/orchestration/values-overwrite-tab-1.yaml
  modules/ROOT/examples/deployment/container/orchestration/values-overwrite-tab-2.yaml
  modules/ROOT/examples/deployment/container/orchestration/values-overwrite-tab-3.yaml
  modules/ROOT/images/deployment/container/what-is-helm.drawio.svg
  modules/ROOT/pages/deployment/container/container-setup.adoc
  modules/ROOT/pages/deployment/container/orchestration.adoc
  modules/ROOT/pages/deployment/container/orchestration/builtin-user-mgmt-secrets-tab-1.adoc
  modules/ROOT/pages/deployment/container/orchestration/builtin-user-mgmt-secrets-tab-2.adoc
  modules/ROOT/pages/deployment/container/orchestration/builtin-user-mgmt-secrets-tab-3.adoc
  modules/ROOT/pages/deployment/container/orchestration/external-user-mgmt-secrets-tab-1.adoc
  modules/ROOT/pages/deployment/container/orchestration/external-user-mgmt-secrets-tab-2.adoc
  modules/ROOT/pages/deployment/container/orchestration/external-user-mgmt-secrets-tab-3.adoc
  modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc
  modules/ROOT/pages/deployment/container/orchestration/secrets-tab-1.adoc
  modules/ROOT/pages/deployment/container/orchestration/secrets-tab-2.adoc
  modules/ROOT/pages/deployment/container/orchestration/secrets-tab-3.adoc
  modules/ROOT/pages/deployment/container/orchestration/val-desc-tab-1.adoc
  modules/ROOT/pages/deployment/container/orchestration/val-desc-tab-2.adoc
  modules/ROOT/pages/deployment/container/orchestration/val-desc-tab-3.adoc
  modules/ROOT/pages/deployment/container/orchestration/values-tab-1.adoc
  modules/ROOT/pages/deployment/container/orchestration/values-tab-2.adoc
  modules/ROOT/pages/deployment/container/orchestration/values-tab-3.adoc
  modules/ROOT/partials/nav.adoc
  site.yml
Labels: documentation

#216 Update Helm Chart
  modules/ROOT/examples/deployment/container/orchestration/generic-secrets-tab-1.yaml
  modules/ROOT/examples/deployment/container/orchestration/generic-secrets-tab-2.yaml
  modules/ROOT/examples/deployment/container/orchestration/generic-secrets-tab-3.yaml
  modules/ROOT/pages/deployment/container/orchestration/generic-secrets-tab-1.adoc
  modules/ROOT/pages/deployment/container/orchestration/generic-secrets-tab-2.adoc
  modules/ROOT/pages/deployment/container/orchestration/generic-secrets-tab-3.adoc
  modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc
Labels: documentation

#217 Moving the tab pages into an own directory
  modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc
  modules/ROOT/pages/deployment/container/orchestration/tab-pages/builtin-user-mgmt-secrets-tab-1.adoc
  modules/ROOT/pages/deployment/container/orchestration/tab-pages/builtin-user-mgmt-secrets-tab-2.adoc
  modules/ROOT/pages/deployment/container/orchestration/tab-pages/builtin-user-mgmt-secrets-tab-3.adoc
  modules/ROOT/pages/deployment/container/orchestration/tab-pages/external-user-mgmt-secrets-tab-1.adoc
  modules/ROOT/pages/deployment/container/orchestration/tab-pages/external-user-mgmt-secrets-tab-2.adoc
  modules/ROOT/pages/deployment/container/orchestration/tab-pages/external-user-mgmt-secrets-tab-3.adoc
  modules/ROOT/pages/deployment/container/orchestration/tab-pages/generic-secrets-tab-1.adoc
  modules/ROOT/pages/deployment/container/orchestration/tab-pages/generic-secrets-tab-2.adoc
  modules/ROOT/pages/deployment/container/orchestration/tab-pages/generic-secrets-tab-3.adoc
  modules/ROOT/pages/deployment/container/orchestration/tab-pages/val-desc-tab-1.adoc
  modules/ROOT/pages/deployment/container/orchestration/tab-pages/val-desc-tab-2.adoc
  modules/ROOT/pages/deployment/container/orchestration/tab-pages/val-desc-tab-3.adoc
  modules/ROOT/pages/deployment/container/orchestration/tab-pages/values-tab-1.adoc
  modules/ROOT/pages/deployment/container/orchestration/tab-pages/values-tab-2.adoc
  modules/ROOT/pages/deployment/container/orchestration/tab-pages/values-tab-3.adoc
Labels: documentation

#219 Manage incomplete uploads
  modules/ROOT/pages/deployment/general/general-info.adoc
  modules/ROOT/pages/deployment/index.adoc
  modules/ROOT/pages/deployment/services/storage-users.adoc
Labels: documentation

#220 Add dependabot.yml
  .github/dependabot.yml
Labels: dependencies

#230 Fix some xrefs
  modules/ROOT/pages/deployment/container/orchestration/tab-pages/values-tab-1.adoc
  modules/ROOT/pages/deployment/container/orchestration/tab-pages/values-tab-2.adoc
  modules/ROOT/pages/deployment/container/orchestration/tab-pages/values-tab-3.adoc
Labels: documentation

#231 typos in orchestration file
  modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc
Labels: documentation

#232 Prepare for ocis beta.7
  site.yml
Labels: deployment

#233 fix some issues in site.yml
  site.yml
Labels: deployment
