Repository owncloud/docs-ocis, pull requests merged in 2024-11, with the labels that each got.

#1043 [docs] add step to configure externalDomain
  modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc
Labels: documentation

#1044 [docs] fix secrets name for s3 credential
  modules/ROOT/examples/deployment/container/orchestration/s3ng-s3-access-key-id-secret-tab-1.yaml
  modules/ROOT/examples/deployment/container/orchestration/s3ng-s3-access-key-id-secret-tab-2.yaml
  modules/ROOT/examples/deployment/container/orchestration/s3ng-s3-access-key-id-secret-tab-3.yaml
Labels: documentation

#1046 Update proxy service
  modules/ROOT/pages/additional-information/knowledge-base.adoc
  modules/ROOT/pages/deployment/services/s-list/ocs.adoc
  modules/ROOT/pages/deployment/services/s-list/proxy.adoc
Labels: documentation

#1047 [master] set ocis 5.0.9 (local build only)
  site.yml
Labels: deployment

#1048 [5.0] set ocis 5.0.9 (global build)
  antora.yml
Labels: deployment

#1051 Fix how to get the space ID documentation
  modules/ROOT/pages/maintenance/space-ids/space-ids.adoc
  modules/ROOT/partials/multi-location/get-bearer-token.adoc
Labels: documentation

#1055 Update bare metal deployments
  modules/ROOT/pages/depl-examples/bare-metal.adoc
  modules/ROOT/pages/depl-examples/minimal-bare-metal.adoc
Labels: documentation

#1057 [5.0] [PR 1055] Update bare metal deployments
  modules/ROOT/pages/depl-examples/bare-metal.adoc
  modules/ROOT/pages/depl-examples/minimal-bare-metal.adoc
Labels: backport

#1058 Small bare metal fixes
  modules/ROOT/pages/depl-examples/bare-metal.adoc
  modules/ROOT/pages/depl-examples/minimal-bare-metal.adoc
Labels: documentation

#1059 [5.0] [PR 1058] Small bare metal fixes
  modules/ROOT/pages/depl-examples/bare-metal.adoc
  modules/ROOT/pages/depl-examples/minimal-bare-metal.adoc
Labels: backport

#1060 [5.0] Fix attributes which are treated different in this branch
  antora.yml
  modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-hetzner.adoc
  modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-prod.adoc
Labels: documentation

#1061 Make SMTP_SENDER a mandatory setting
  modules/ROOT/partials/depl-examples/ubuntu-compose/shared-setup.adoc
Labels: documentation

#1062 [5.0] [PR 1061] Make SMTP_SENDER a mandatory setting
  modules/ROOT/partials/depl-examples/ubuntu-compose/shared-setup.adoc
Labels: backport

#1063 Add a note for all services that must be started manually
  modules/ROOT/pages/deployment/services/s-list/antivirus.adoc
  modules/ROOT/pages/deployment/services/s-list/audit.adoc
  modules/ROOT/pages/deployment/services/s-list/auth-app.adoc
  modules/ROOT/pages/deployment/services/s-list/collaboration.adoc
  modules/ROOT/pages/deployment/services/s-list/invitations.adoc
  modules/ROOT/pages/deployment/services/s-list/notifications.adoc
  modules/ROOT/pages/deployment/services/s-list/policies.adoc
Labels: documentation

#1064 Add that the S3 blob is encrypted automatically on the AWS side
  modules/ROOT/pages/deployment/storage/s3.adoc
Labels: documentation

#1065 [5.0] [PR 1064] Add that the S3 blob is encrypted automatically on the AWS side
  modules/ROOT/pages/deployment/storage/s3.adoc
Labels: documentation

#1068 [5.0] [PR 1066] del_stray_word_ocis_bin_systemd.adoc
  modules/ROOT/partials/deployment/systemd.adoc
Labels: backport

#1067 Update the docker compose deployment example
  modules/ROOT/partials/depl-examples/ubuntu-compose/shared-setup.adoc
Labels: documentation

#1069 [5.0] [PR 1067] Update the docker compose deployment example
  modules/ROOT/partials/depl-examples/ubuntu-compose/shared-setup.adoc
Labels: backport

#1074 [5.0] [PR 1073] Add metrics info for stand alone services
  modules/ROOT/pages/monitoring/prometheus.adoc
Labels: backport

#1072 Add a command to show the final config in compose deployments
  modules/ROOT/partials/depl-examples/ubuntu-compose/shared-setup.adoc
Labels: documentation

#1070 The antivirtus service has additional memory requirements
  modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-hetzner.adoc
  modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-prod.adoc
  modules/ROOT/pages/deployment/services/s-list/antivirus.adoc
Labels: documentation

#1077 Update docker compose update details
  modules/ROOT/partials/depl-examples/ubuntu-compose/shared-setup.adoc
Labels: documentation

#1075 [5.0] [PR 1072] Add a command to show the final config in compose deployments
  modules/ROOT/partials/depl-examples/ubuntu-compose/shared-setup.adoc
Labels: backport

#1078 Typo fixes
  modules/ROOT/pages/maintenance/space-ids/space-ids.adoc
  modules/ROOT/pages/maintenance/user-ids/user-ids.adoc
  modules/ROOT/partials/depl-examples/ubuntu-compose/shared-setup.adoc
Labels: documentation
