Repository owncloud/docs-ocis, pull requests merged in 2024-06, with the labels that each got.

#855 Update Thumbnail service
  modules/ROOT/pages/deployment/services/s-list/thumbnails.adoc
Labels: documentation

#856 Update Restore Trash-Bins Items in storage-users
  modules/ROOT/pages/deployment/services/s-list/storage-users.adoc
Labels: documentation

#857 Fix command typo in generate-index.js
  ext-antora/generate-index.js
Labels: bug

#858 [5.0] [PR 857] Fix command typo in generate-index.js
  ext-antora/generate-index.js
Labels: backport

#859 Backup Considerations
  modules/ROOT/pages/maintenance/b-r/backup_considerations.adoc
  modules/ROOT/partials/nav.adoc
Labels: documentation

#861 [5.0] [PR 859] Backup Considerations
  modules/ROOT/pages/maintenance/b-r/backup_considerations.adoc
  modules/ROOT/partials/nav.adoc
Labels: backport

#860 Thumbnails and SecureView
  modules/ROOT/pages/deployment/services/s-list/thumbnails.adoc
Labels: documentation

#863 Improve and fix the Minimal Bare Metal deployment
  modules/ROOT/pages/depl-examples/minimal-bare-metal.adoc
  modules/ROOT/pages/deployment/general/general-info.adoc
  modules/ROOT/partials/multi-location/idm-https-reverse-proxy.adoc
Labels: deployment

#867 Update repo README
  README.md
Labels: deployment

#870 Partial backport of #866
  README.md
  modules/ROOT/pages/deployment/services/s-list/eventhistory.adoc
  modules/ROOT/pages/deployment/services/s-list/frontend.adoc
  modules/ROOT/pages/deployment/services/s-list/gateway.adoc
  modules/ROOT/pages/deployment/services/s-list/graph.adoc
  modules/ROOT/pages/deployment/services/s-list/postprocessing.adoc
  modules/ROOT/pages/deployment/services/s-list/proxy.adoc
  modules/ROOT/pages/deployment/services/s-list/settings.adoc
  modules/ROOT/pages/deployment/services/s-list/storage-system.adoc
  modules/ROOT/pages/deployment/services/s-list/storage-users.adoc
  modules/ROOT/pages/deployment/services/s-list/userlog.adoc
  modules/ROOT/partials/deployment/services/log-service-ecosystem.adoc
  modules/ROOT/partials/multi-location/caching-list.adoc
Labels: backport

#871 Added custom ca chain to helm doc
  modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc
Labels: documentation

#872 Add backchannel logout inability in IDP
  modules/ROOT/pages/deployment/services/s-list/idp.adoc
Labels: documentation

#875 Correct the ocis-actual-version attribute for local builds
  site.yml
Labels: deployment

#874 Correcting the latest ocis stable version rendered for 5.0
  antora.yml
Labels: deployment

#876 [5.0] [PR 875] Correct the ocis-actual-version attribute for local builds
  site.yml
Labels: backport
