Repository owncloud/docs-ocis, pull requests merged in 2024-02, with the labels that each got.

#704 Make the ocis content versioned
  antora.yml
  modules/ROOT/pages/conf-examples/office/ext-files/app-registry.adoc
  modules/ROOT/pages/conf-examples/office/ext-files/docker-compose.adoc
  modules/ROOT/pages/conf-examples/office/ext-files/env.adoc
  modules/ROOT/pages/conf-examples/office/ext-files/wopiserver.adoc
  modules/ROOT/pages/conf-examples/office/office-integration.adoc
  modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc
  modules/ROOT/pages/deployment/services/env-vars-special-scope.adoc
  modules/ROOT/pages/deployment/services/s-list/policies.adoc
  modules/ROOT/pages/deployment/wopi/wopi.adoc
  modules/ROOT/partials/deployment/services/env-and-yaml.adoc
Labels: deployment

#705 Some small fixes to ease versioning
  modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc
  modules/ROOT/pages/deployment/wopi/wopi.adoc
  site.yml
Labels: documentation, deployment

#706 Add ES example yml
  es-docker-compose.yml
Labels: deployment

#707 Fix search index generation
  ext-antora/generate-index.js
Labels: deployment

#710 Correct the version in .drone.star in 4.0
  .drone.star
Labels: deployment

#711 Minor fix for completeness in .drone.star in 4.0
  .drone.star
Labels: deployment

#712 Make the 5.0 release point to the correct ocis branches.
  antora.yml
  site.yml
Labels: deployment

#713 Added a page with changed envvars based on the version
  modules/ROOT/pages/deployment/services/env-var-changes.adoc
  modules/ROOT/partials/deployment/services/general-info/env-var-changes/added-4.0.5-5.0.0.adoc
  modules/ROOT/partials/nav.adoc
Labels: documentation

#715 [5.0] [PR 713] Added a page with changed envvars based on the version
  modules/ROOT/pages/deployment/services/env-var-changes.adoc
  modules/ROOT/partials/deployment/services/general-info/env-var-changes/added-4.0.5-5.0.0.adoc
  modules/ROOT/partials/nav.adoc
Labels: backport

#717 Fix antora.yml for master
  antora.yml
Labels: deployment

#718 Improve changed envvar list by version
  antora.yml
  modules/ROOT/pages/deployment/services/env-var-changes.adoc
  modules/ROOT/partials/deployment/services/general-info/env-var-changes/added-4.0.5-5.0.0.adoc
Labels: documentation

#722 ES index update
  docs/new-version-branch.md
  ext-antora/generate-index.js
Labels: deployment

#723 [5.0] [PR 722] ES index update
  docs/new-version-branch.md
  ext-antora/generate-index.js
Labels: backport

#724 [4.0] [PR 722] ES index update
  docs/new-version-branch.md
  ext-antora/generate-index.js
Labels: backport

#726 Add envvars to yaml config
  modules/ROOT/pages/deployment/services/env-var-note.adoc
  modules/ROOT/partials/deployment/services/env-and-yaml.adoc
Labels: documentation

#727 [5.0] [PR 726] Add envvars to yaml config
  modules/ROOT/pages/deployment/services/env-var-note.adoc
  modules/ROOT/partials/deployment/services/env-and-yaml.adoc
Labels: backport

#728 Make local/global envvars in caching more clear
  modules/ROOT/pages/deployment/services/s-list/eventhistory.adoc
  modules/ROOT/pages/deployment/services/s-list/frontend.adoc
  modules/ROOT/pages/deployment/services/s-list/gateway.adoc
  modules/ROOT/pages/deployment/services/s-list/graph.adoc
  modules/ROOT/pages/deployment/services/s-list/postprocessing.adoc
  modules/ROOT/pages/deployment/services/s-list/proxy.adoc
  modules/ROOT/pages/deployment/services/s-list/settings.adoc
  modules/ROOT/pages/deployment/services/s-list/storage-system.adoc
  modules/ROOT/pages/deployment/services/s-list/storage-users.adoc
  modules/ROOT/pages/deployment/services/s-list/userlog.adoc
  modules/ROOT/partials/multi-location/caching-list.adoc
Labels: documentation

#729 [5.0] [PR 728] Make local/global envvars in caching more clear
  modules/ROOT/pages/deployment/services/s-list/eventhistory.adoc
  modules/ROOT/pages/deployment/services/s-list/frontend.adoc
  modules/ROOT/pages/deployment/services/s-list/gateway.adoc
  modules/ROOT/pages/deployment/services/s-list/graph.adoc
  modules/ROOT/pages/deployment/services/s-list/postprocessing.adoc
  modules/ROOT/pages/deployment/services/s-list/proxy.adoc
  modules/ROOT/pages/deployment/services/s-list/settings.adoc
  modules/ROOT/pages/deployment/services/s-list/storage-system.adoc
  modules/ROOT/pages/deployment/services/s-list/storage-users.adoc
  modules/ROOT/pages/deployment/services/s-list/userlog.adoc
  modules/ROOT/partials/multi-location/caching-list.adoc
Labels: backport

#730 Remove orphaned and unused files
  modules/ROOT/pages/deployment/configuration/_email-config.adoc
  modules/ROOT/pages/deployment/configuration/_external-user-management.adoc
  modules/ROOT/pages/deployment/configuration/_index.adoc
  modules/ROOT/pages/deployment/configuration/_ocis-config.adoc
  modules/ROOT/pages/deployment/configuration/_office-integrations.adoc
  modules/ROOT/pages/deployment/configuration/_roles-permissions.adoc
  modules/ROOT/pages/deployment/configuration/_storage.adoc
Labels: documentation

#731 [5.0] [PR 730] Remove orphaned and unused files
  modules/ROOT/pages/deployment/configuration/_email-config.adoc
  modules/ROOT/pages/deployment/configuration/_external-user-management.adoc
  modules/ROOT/pages/deployment/configuration/_index.adoc
  modules/ROOT/pages/deployment/configuration/_ocis-config.adoc
  modules/ROOT/pages/deployment/configuration/_office-integrations.adoc
  modules/ROOT/pages/deployment/configuration/_roles-permissions.adoc
  modules/ROOT/pages/deployment/configuration/_storage.adoc
Labels: backport

#732 Update the General Info page with $HOME and ~ for config and data dir
  modules/ROOT/pages/deployment/binary/binary-setup.adoc
  modules/ROOT/pages/deployment/general/general-info.adoc
Labels: documentation

#733 [5.0] [PR 732] Update the General Info page with $HOME and ~ for config and data dir
  modules/ROOT/pages/deployment/binary/binary-setup.adoc
  modules/ROOT/pages/deployment/general/general-info.adoc
Labels: backport

#734 Update caching and persistence
  modules/ROOT/pages/deployment/services/caching.adoc
  modules/ROOT/pages/deployment/services/s-list/antivirus.adoc
  modules/ROOT/pages/deployment/services/s-list/audit.adoc
  modules/ROOT/pages/deployment/services/s-list/clientlog.adoc
  modules/ROOT/pages/deployment/services/s-list/eventhistory.adoc
  modules/ROOT/pages/deployment/services/s-list/frontend.adoc
  modules/ROOT/pages/deployment/services/s-list/gateway.adoc
  modules/ROOT/pages/deployment/services/s-list/graph.adoc
  modules/ROOT/pages/deployment/services/s-list/notifications.adoc
  modules/ROOT/pages/deployment/services/s-list/policies.adoc
  modules/ROOT/pages/deployment/services/s-list/postprocessing.adoc
  modules/ROOT/pages/deployment/services/s-list/proxy.adoc
  modules/ROOT/pages/deployment/services/s-list/search.adoc
  modules/ROOT/pages/deployment/services/s-list/settings.adoc
  modules/ROOT/pages/deployment/services/s-list/sharing.adoc
  modules/ROOT/pages/deployment/services/s-list/sse.adoc
  modules/ROOT/pages/deployment/services/s-list/storage-system.adoc
  modules/ROOT/pages/deployment/services/s-list/storage-users.adoc
  modules/ROOT/pages/deployment/services/s-list/userlog.adoc
  modules/ROOT/partials/multi-location/caching-list.adoc
  modules/ROOT/partials/multi-location/event-bus.adoc
Labels: documentation

#735 [5.0] [PR 734] Update caching and persistence
  modules/ROOT/pages/deployment/services/caching.adoc
  modules/ROOT/pages/deployment/services/s-list/antivirus.adoc
  modules/ROOT/pages/deployment/services/s-list/audit.adoc
  modules/ROOT/pages/deployment/services/s-list/clientlog.adoc
  modules/ROOT/pages/deployment/services/s-list/eventhistory.adoc
  modules/ROOT/pages/deployment/services/s-list/frontend.adoc
  modules/ROOT/pages/deployment/services/s-list/gateway.adoc
  modules/ROOT/pages/deployment/services/s-list/graph.adoc
  modules/ROOT/pages/deployment/services/s-list/notifications.adoc
  modules/ROOT/pages/deployment/services/s-list/policies.adoc
  modules/ROOT/pages/deployment/services/s-list/postprocessing.adoc
  modules/ROOT/pages/deployment/services/s-list/proxy.adoc
  modules/ROOT/pages/deployment/services/s-list/search.adoc
  modules/ROOT/pages/deployment/services/s-list/settings.adoc
  modules/ROOT/pages/deployment/services/s-list/sharing.adoc
  modules/ROOT/pages/deployment/services/s-list/sse.adoc
  modules/ROOT/pages/deployment/services/s-list/storage-system.adoc
  modules/ROOT/pages/deployment/services/s-list/storage-users.adoc
  modules/ROOT/pages/deployment/services/s-list/userlog.adoc
  modules/ROOT/partials/multi-location/caching-list.adoc
  modules/ROOT/partials/multi-location/event-bus.adoc
Labels: backport

#719 [5.0] [PR 718] Improve changed envvar list by version
  antora.yml
  modules/ROOT/pages/deployment/services/env-var-changes.adoc
  modules/ROOT/partials/deployment/services/general-info/env-var-changes/added-4.0.5-5.0.0.adoc
Labels: backport
