Repository owncloud/docs-ocis, pull requests merged in 2024-05, with the labels that each got.

#809 Fix typo in general-info.adoc
  modules/ROOT/pages/deployment/general/general-info.adoc
Labels: documentation

#811 [5.0] [PR 809] Fix typo in general-info.adoc
  modules/ROOT/pages/deployment/general/general-info.adoc
Labels: backport

#810 Fix ps command in binary description
  modules/ROOT/pages/deployment/binary/binary-setup.adoc
Labels: documentation

#812 [5.0] [PR 810] Fix ps command in binary description
  modules/ROOT/pages/deployment/binary/binary-setup.adoc
Labels: backport

#814 [5.0] [PR 806] Fix: ocmproviders.json in ocm.adoc
  modules/ROOT/pages/deployment/services/s-list/ocm.adoc
Labels: backport

#813 [5.0] [PR 805] Fix: Remove mDNS from binary-setup.adoc ?
  modules/ROOT/pages/deployment/binary/binary-setup.adoc
Labels: backport

#819 Referencing Infinite Scale 5.0.3
  antora.yml
  site.yml
Labels: deployment

#822 [5.0] [PR 821] spell initialisation -> initialization
  modules/ROOT/pages/depl-examples/minimal-bare-metal.adoc
  modules/ROOT/pages/deployment/general/general-info.adoc
Labels: backport

#823 Small site.yml update for master only
  site.yml
Labels: deployment

#824 Update storage-users uploads sessions command
  modules/ROOT/pages/deployment/services/s-list/storage-users.adoc
Labels: documentation

#825 Reset Admin Password
  modules/ROOT/pages/deployment/general/general-info.adoc
  modules/ROOT/pages/deployment/services/s-list/idm.adoc
  modules/ROOT/pages/maintenance/commands/commands.adoc
  modules/ROOT/pages/migration/upgrading_4.0.0_5.0.0.adoc
  modules/ROOT/partials/multi-location/compose-version.adoc
Labels: documentation

#828 [5.0] [PR 827] Reset password fix for docker compose
  modules/ROOT/pages/deployment/general/general-info.adoc
Labels: backport

#829 Text update resetpassword from feedback.
  modules/ROOT/pages/deployment/general/general-info.adoc
Labels: documentation

#830 [5.0] [PR 829] Text update resetpassword from feedback.
  modules/ROOT/pages/deployment/general/general-info.adoc
Labels: backport

#831 Render fix in the general-info page
  modules/ROOT/pages/deployment/general/general-info.adoc
Labels: documentation

#832 [5.0] [PR 831] Render fix in the general-info page
  modules/ROOT/pages/deployment/general/general-info.adoc
Labels: backport

#833 Clarify text for reset admin passwd
  modules/ROOT/pages/deployment/general/general-info.adoc
Labels: documentation

#834 [5.0] [PR 833] Clarify text for reset admin passwd
  modules/ROOT/pages/deployment/general/general-info.adoc
Labels: backport

#835 chore: report CI result to builds channel
  .drone.star
Labels: deployment

#836 [5.0] [PR 835] chore: report CI result to builds channel
  .drone.star
Labels: backport

#841 Make ocis 5.0.4 the actual version
  antora.yml
  site.yml
Labels: deployment

#842 Add text how to manually define which services will be started
  modules/ROOT/pages/deployment/general/general-info.adoc
Labels: documentation

#844 [5.0] [PR 842] Add text how to manually define which services will be started
  modules/ROOT/pages/deployment/general/general-info.adoc
Labels: backport

#846 Fix site.yml for local rendering only
  site.yml
Labels: deployment

#847 Update prometheus.adoc - correct wrong envvar used
  modules/ROOT/pages/monitoring/prometheus.adoc
Labels: documentation

#848 [5.0] [PR 847] Update prometheus.adoc - correct wrong envvar used
  modules/ROOT/pages/monitoring/prometheus.adoc
Labels: backport
