Repository owncloud/docs-ocis, pull requests merged in 2024-09, with the labels that each got.

#975 [5.0] Fix update in depl examples
  modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-hetzner.adoc
  modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-prod.adoc
Labels: documentation

#977 Update the ocm service description
  modules/ROOT/pages/deployment/services/s-list/ocm.adoc
Labels: documentation

#976 Local only, ocis 5.0.7
  site.yml
Labels: deployment

#978 [5.0] [PR 976] Local only, ocis 5.0.7
  site.yml
Labels: backport

#980 Reordering some text in notifications to improve readability
  modules/ROOT/pages/deployment/services/s-list/notifications.adoc
Labels: documentation

#981 [5.0] [PR 980] Reordering some text in notifications to improve readability
  modules/ROOT/pages/deployment/services/s-list/notifications.adoc
Labels: backport

#982 Only one instance per deployment
  modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-hetzner.adoc
  modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-prod.adoc
Labels: documentation

#983 [5.0] [PR 982] Only one instance per deployment
  modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-hetzner.adoc
  modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-prod.adoc
Labels: backport

#984 Add deployment example: ScienceMesh Federation
  modules/ROOT/images/depl-examples/federation/science_mesh/sm_OpenCloudMesh_min.png
  modules/ROOT/images/depl-examples/federation/science_mesh/sm_federation_a_setup.png
  modules/ROOT/images/depl-examples/federation/science_mesh/sm_federation_b_setup.png
  modules/ROOT/images/depl-examples/federation/science_mesh/sm_invitations.png
  modules/ROOT/images/depl-examples/federation/science_mesh/sm_science_mesh_logo.svg
  modules/ROOT/images/depl-examples/federation/science_mesh/sm_select_app.png
  modules/ROOT/images/depl-examples/federation/science_mesh/sm_user_accept_token.png
  modules/ROOT/images/depl-examples/federation/science_mesh/sm_user_generate_invite.png
  modules/ROOT/images/depl-examples/federation/science_mesh/sm_user_resource_shared.png
  modules/ROOT/images/depl-examples/federation/science_mesh/sm_user_share_resource_search.png
  modules/ROOT/images/depl-examples/federation/science_mesh/sm_user_share_resource_selected.png
  modules/ROOT/images/depl-examples/federation/science_mesh/sm_user_token_generated.png
  modules/ROOT/pages/depl-examples/federation/sciencemesh.adoc
  modules/ROOT/partials/nav.adoc
Labels: documentation

#985 Local only, ocis 6.4.0
  site.yml
Labels: deployment

#954 [5.0] only selective backport of session commands
  modules/ROOT/pages/deployment/services/s-list/storage-users.adoc
  modules/ROOT/pages/maintenance/commands/commands.adoc
Labels: documentation

#960 [5.0] Selective backport: confingurable volumes in deployment example
  modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-hetzner.adoc
  modules/ROOT/partials/depl-examples/ubuntu-compose/shared-setup.adoc
Labels: documentation

#987 [5.0] [PR 985] Local only, ocis 6.4.0
  site.yml
Labels: backport

#989 Set 5.0.7 as default in the 5.0 branch
  antora.yml
Labels: documentation

#988 Update Collaboration Service
  modules/ROOT/pages/deployment/services/s-list/collaboration.adoc
Labels: documentation

#990 fix migration command
  modules/ROOT/pages/maintenance/commands/rolling-back-and-forward.adoc
Labels: documentation

#991 [5.0] [PR 990] fix migration command
  modules/ROOT/pages/maintenance/commands/rolling-back-and-forward.adoc
Labels: backport

#992 Update compose deployments based on feedback
  modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-hetzner.adoc
  modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-prod.adoc
  modules/ROOT/partials/depl-examples/ubuntu-compose/shared-setup.adoc
Labels: documentation

#996 [5.0] [PR 992] Update compose deployments based on feedback
  modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-hetzner.adoc
  modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-prod.adoc
  modules/ROOT/partials/depl-examples/ubuntu-compose/shared-setup.adoc
Labels: backport
