Repository owncloud/docs-ocis, pull requests merged in 2024-10, with the labels that each got.

#998 [5.0] Fix using the correct attribute
  modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-prod.adoc
Labels: documentation

#979 Local only, ocis 5.0.8
  site.yml
Labels: deployment

#999 Make 5.0.8 default in the 5.0 branch
  antora.yml
Labels: deployment

#1001 Removing metadata backend info from docs
  modules/ROOT/pages/deployment/services/s-list/storage-system.adoc
  modules/ROOT/pages/deployment/services/s-list/storage-users.adoc
  modules/ROOT/pages/prerequisites/prerequisites.adoc
  modules/ROOT/pages/prerequisites/xattrs.adoc
Labels: documentation

#1000 Describe the purpose of the storage-system service
  modules/ROOT/pages/deployment/services/s-list/storage-system.adoc
Labels: documentation

#1002 [5.0] [PR 1000] Describe the purpose of the storage-system service
  modules/ROOT/pages/deployment/services/s-list/storage-system.adoc
Labels: backport

#1003 Add a title text to the envvars list block in auth-app startup
  modules/ROOT/pages/deployment/services/s-list/auth-app.adoc
Labels: documentation

#1005 General Info render fixes
  modules/ROOT/pages/deployment/general/general-info.adoc
Labels: documentation

#1006 [5.0] [PR 1005] General Info render fixes
  modules/ROOT/pages/deployment/general/general-info.adoc
Labels: backport

#1004 Update the Graph Service description
  modules/ROOT/pages/deployment/services/s-list/graph.adoc
  modules/ROOT/partials/depl-examples/ubuntu-compose/shared-setup.adoc
  site.yml
Labels: documentation

#1007 Registry and cache store updates
  modules/ROOT/pages/deployment/services/caching.adoc
  modules/ROOT/pages/deployment/services/env-vars-special-scope.adoc
  modules/ROOT/pages/deployment/services/registry.adoc
  modules/ROOT/pages/deployment/services/s-list/frontend.adoc
  modules/ROOT/pages/deployment/services/s-list/gateway.adoc
  modules/ROOT/pages/deployment/services/s-list/graph.adoc
  modules/ROOT/pages/deployment/services/s-list/nats.adoc
  modules/ROOT/pages/deployment/services/s-list/postprocessing.adoc
  modules/ROOT/pages/deployment/services/s-list/proxy.adoc
  modules/ROOT/pages/deployment/services/s-list/settings.adoc
  modules/ROOT/pages/deployment/services/s-list/storage-system.adoc
  modules/ROOT/pages/deployment/services/s-list/storage-users.adoc
  modules/ROOT/pages/deployment/services/s-list/thumbnails.adoc
  modules/ROOT/pages/deployment/services/s-list/userlog.adoc
  modules/ROOT/partials/multi-location/caching-list.adoc
  modules/ROOT/partials/nav.adoc
Labels: documentation

#1010 Make the dynamics of stable/production more robust
  antora.yml
  modules/ROOT/pages/depl-examples/bare-metal.adoc
  modules/ROOT/pages/depl-examples/minimal-bare-metal.adoc
  modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-hetzner.adoc
  modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-prod.adoc
  modules/ROOT/pages/deployment/general/general-info.adoc
  modules/ROOT/pages/deployment/services/s-list/graph.adoc
  modules/ROOT/pages/migration/upgrading-ocis.adoc
  modules/ROOT/pages/migration/upgrading_2.0.0_3.0.0.adoc
  modules/ROOT/pages/migration/upgrading_3.0.0_4.0.0.adoc
  modules/ROOT/pages/migration/upgrading_4.0.0_5.0.0.adoc
  modules/ROOT/pages/quickguide/quickguide.adoc
  modules/ROOT/partials/deployment/services/translations.adoc
  modules/ROOT/partials/multi-location/compose-version-production.adoc
  modules/ROOT/partials/multi-location/compose-version-rolling.adoc
  modules/ROOT/partials/multi-location/compose-version.adoc
  site.yml
Labels: documentation

#1011 Fix ocis-downloadpage-url attribute usage
  modules/ROOT/pages/depl-examples/bare-metal.adoc
  modules/ROOT/pages/depl-examples/minimal-bare-metal.adoc
  modules/ROOT/pages/migration/upgrading-ocis.adoc
  modules/ROOT/pages/migration/upgrading_2.0.0_3.0.0.adoc
  modules/ROOT/pages/migration/upgrading_3.0.0_4.0.0.adoc
  modules/ROOT/pages/migration/upgrading_4.0.0_5.0.0.adoc
  modules/ROOT/pages/quickguide/quickguide.adoc
  site.yml
Labels: backport

#1012 New thumbnail generator for container deployments
  modules/ROOT/pages/depl-examples/bare-metal.adoc
  modules/ROOT/pages/depl-examples/minimal-bare-metal.adoc
  modules/ROOT/pages/deployment/services/s-list/thumbnails.adoc
Labels: documentation

#1014 Fix envvar name in collaboration service
  modules/ROOT/pages/deployment/services/s-list/collaboration.adoc
Labels: documentation

#1015 Prepare for ocis 6.6.0 (local build relevant only)
  site.yml
Labels: deployment

#1017 docs: updating docker command for getting user id
  modules/ROOT/pages/deployment/container/container-setup.adoc
Labels: documentation

#1018 [5.0] [PR 1017] docs: updating docker command for getting user id
  modules/ROOT/pages/deployment/container/container-setup.adoc
Labels: backport

#1019 Add antivirus workers
  modules/ROOT/pages/deployment/services/s-list/antivirus.adoc
Labels: documentation

#1020 Fix ports-used
  modules/ROOT/pages/deployment/services/ports-used.adoc
Labels: documentation

#1022 Update collaboration using a store + partial text fixes
  modules/ROOT/pages/deployment/services/s-list/collaboration.adoc
  modules/ROOT/partials/multi-location/caching-list.adoc
Labels: documentation

#1024 Add SSE keep alive
  modules/ROOT/pages/deployment/services/s-list/sse.adoc
Labels: documentation

#1025 Proper naming of store attribute/partial
  modules/ROOT/pages/deployment/services/caching.adoc
  modules/ROOT/pages/deployment/services/s-list/activitylog.adoc
  modules/ROOT/pages/deployment/services/s-list/collaboration.adoc
  modules/ROOT/pages/deployment/services/s-list/eventhistory.adoc
  modules/ROOT/pages/deployment/services/s-list/frontend.adoc
  modules/ROOT/pages/deployment/services/s-list/gateway.adoc
  modules/ROOT/pages/deployment/services/s-list/graph.adoc
  modules/ROOT/pages/deployment/services/s-list/postprocessing.adoc
  modules/ROOT/pages/deployment/services/s-list/proxy.adoc
  modules/ROOT/pages/deployment/services/s-list/settings.adoc
  modules/ROOT/pages/deployment/services/s-list/storage-system.adoc
  modules/ROOT/pages/deployment/services/s-list/storage-users.adoc
  modules/ROOT/pages/deployment/services/s-list/userlog.adoc
  modules/ROOT/partials/multi-location/cache-store.adoc
Labels: documentation

#1026 ocis 6.6.1 rolling (local build relevant only)
  site.yml
Labels: deployment

#1027 [5.0] [PR 1026] ocis 6.6.1 rolling (local build relevant only)
  site.yml
Labels: backport

#1030 Use tag filtering and add comment in various pages
  modules/ROOT/pages/deployment/services/s-list/activitylog.adoc
  modules/ROOT/pages/deployment/services/s-list/collaboration.adoc
  modules/ROOT/pages/deployment/services/s-list/eventhistory.adoc
  modules/ROOT/pages/deployment/services/s-list/frontend.adoc
  modules/ROOT/pages/deployment/services/s-list/gateway.adoc
  modules/ROOT/pages/deployment/services/s-list/graph.adoc
  modules/ROOT/pages/deployment/services/s-list/notifications.adoc
  modules/ROOT/pages/deployment/services/s-list/postprocessing.adoc
  modules/ROOT/pages/deployment/services/s-list/proxy.adoc
  modules/ROOT/pages/deployment/services/s-list/settings.adoc
  modules/ROOT/pages/deployment/services/s-list/storage-system.adoc
  modules/ROOT/pages/deployment/services/s-list/storage-users.adoc
  modules/ROOT/pages/deployment/services/s-list/userlog.adoc
  modules/ROOT/partials/multi-location/cache-store.adoc
Labels: documentation

#1031 Relocate and update the container setup page
  modules/ROOT/pages/depl-examples/container-setup.adoc
  modules/ROOT/partials/nav.adoc
Labels: documentation

#1032 [5.0] [PR 1031] Relocate and update the container setup page
  modules/ROOT/pages/depl-examples/container-setup.adoc
  modules/ROOT/partials/nav.adoc
Labels: backport

#1033 Single character typo fix in maintenance commands page
  modules/ROOT/pages/maintenance/commands/commands.adoc
Labels: documentation

#1035 [5.0] Remove CLI trash purge-empty-dirs
  modules/ROOT/pages/maintenance/commands/commands.adoc
  modules/ROOT/pages/maintenance/commands/trash.adoc
Labels: documentation

#1036 Fix path for cli --basePath parameter
  modules/ROOT/pages/maintenance/commands/commands.adoc
Labels: documentation

#1037 [5.0] [PR 1036] Fix path for cli --basePath parameter
  modules/ROOT/pages/maintenance/commands/commands.adoc
Labels: backport

#1038 Update the compose examples to be ready to upgrade for the next release
  modules/ROOT/partials/depl-examples/ubuntu-compose/shared-setup.adoc
Labels: documentation
