Repository owncloud/docs-ocis, pull requests merged in 2025-01, with the labels that each got.

#1105 Extension: Implement dynamic loading attributes
  .drone.star
  .gitignore
  ext-antora/attributes-used-in-antora-yml.js
  ext-antora/attributes-used-in-site-yml.js
  ext-antora/comp-version.js
  ext-antora/load-global-site-attributes.js
  package-lock.json
  package.json
  site.yml
  yarn.lock
Labels: deployment, dependencies

#1106 [7.0][1105] Extension: Implement dynamic loading attributes
  .drone.star
  .gitignore
  ext-antora/attributes-used-in-antora-yml.js
  ext-antora/attributes-used-in-site-yml.js
  ext-antora/comp-version.js
  ext-antora/load-global-site-attributes.js
  package-lock.json
  package.json
  site.yml
  yarn.lock
Labels: backport

#1108 Update antora extension to print component, versions ans files
  ext-antora/comp-version.js
Labels: deployment

#1109 [7.0] [PR 1108] Update antora extension to print component, versions and files
  ext-antora/comp-version.js
Labels: backport

#1110 [5.0] [PR 1108] Update antora extension to print component, versions and files
  ext-antora/comp-version.js
Labels: backport

#1112 docs: fix typo in deployment general
  modules/ROOT/pages/deployment/general/ocis-init.adoc
Labels: documentation, Topic:Documentation

#1113 [master] [PR 1112] docs: fix typo in deployment general
  modules/ROOT/pages/deployment/general/ocis-init.adoc
Labels: backport

#1114 [5.0] [PR 1112] docs: fix typo in deployment general
  modules/ROOT/pages/deployment/general/ocis-init.adoc
Labels: backport

#1115 Changes necessary for 7.1
  .drone.star
  antora.yml
  site.yml
Labels: deployment

#1118 [7.1] [PR 1116] Fix the delta range for envvars
  modules/ROOT/pages/deployment/services/env-var-changes.adoc
Labels: backport

#1120 [7.1] [PR 1117] Update container-setup.adoc
  modules/ROOT/pages/depl-examples/container-setup.adoc
Labels: backport

#1121 [7.0] [PR 1117] Update container-setup.adoc
  modules/ROOT/pages/depl-examples/container-setup.adoc
Labels: backport

#1119 Changes for 7.1
  modules/ROOT/pages/deployment/services/s-list/notifications.adoc
  modules/ROOT/pages/deployment/services/s-list/settings.adoc
  modules/ROOT/pages/maintenance/commands/changed-cli.adoc
  modules/ROOT/pages/maintenance/commands/commands.adoc
  modules/ROOT/pages/migration/upgrading-ocis.adoc
  modules/ROOT/pages/migration/upgrading_7.0.0_7.1.0.adoc
Labels: documentation

#1123 [7.1] [PR 1119] Changes for 7.1
  modules/ROOT/pages/deployment/services/s-list/notifications.adoc
  modules/ROOT/pages/deployment/services/s-list/settings.adoc
  modules/ROOT/pages/maintenance/commands/changed-cli.adoc
  modules/ROOT/pages/maintenance/commands/commands.adoc
  modules/ROOT/pages/migration/upgrading-ocis.adoc
  modules/ROOT/pages/migration/upgrading_7.0.0_7.1.0.adoc
Labels: backport

#1126 Add Find Orphaned Files Antora extension
  ext-antora/find-orphaned-files.js
  site.yml
Labels: deployment

#1127 Remove shell based helpers
  bin/find-orphaned-adoc-files
  bin/find-orphaned-attachment-files
  bin/find-orphaned-base
  bin/find-orphaned-example-files
  bin/find-orphaned-image-files
Labels: deployment

#1125 Remove all occurrences and references of binary installations
  modules/ROOT/pages/architecture/architecture.adoc
  modules/ROOT/pages/conf-examples/search/configure-search.adoc
  modules/ROOT/pages/depl-examples/bare-metal.adoc
  modules/ROOT/pages/depl-examples/minimal-bare-metal.adoc
  modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-prod.adoc
  modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc
  modules/ROOT/pages/deployment/general/general-info.adoc
  modules/ROOT/pages/deployment/general/ocis-init.adoc
  modules/ROOT/pages/deployment/index.adoc
  modules/ROOT/pages/deployment/services/env-var-note.adoc
  modules/ROOT/pages/deployment/services/env-vars-special-scope.adoc
  modules/ROOT/pages/deployment/services/registry.adoc
  modules/ROOT/pages/deployment/services/s-list/audit.adoc
  modules/ROOT/pages/deployment/services/s-list/collaboration.adoc
  modules/ROOT/pages/deployment/services/s-list/postprocessing.adoc
  modules/ROOT/pages/deployment/services/s-list/storage-users.adoc
  modules/ROOT/pages/deployment/services/s-list/thumbnails.adoc
  modules/ROOT/pages/deployment/storage/general-considerations.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/maintenance/b-r/backup.adoc
  modules/ROOT/pages/maintenance/b-r/restore.adoc
  modules/ROOT/pages/maintenance/commands/commands.adoc
  modules/ROOT/pages/maintenance/commands/rolling-back-and-forward.adoc
  modules/ROOT/pages/migration/upgrading_7.0.0_7.1.0.adoc
  modules/ROOT/pages/prerequisites/prerequisites.adoc
  modules/ROOT/pages/quickguide/quickguide.adoc
  modules/ROOT/partials/deployment/apache_80_example.adoc
  modules/ROOT/partials/deployment/apache_harden_ssl.adoc
  modules/ROOT/partials/deployment/apache_proxy_example.adoc
  modules/ROOT/partials/deployment/dependent_startup.adoc
  modules/ROOT/partials/deployment/nginx_80_example.adoc
  modules/ROOT/partials/deployment/nginx_harden_ssl.adoc
  modules/ROOT/partials/deployment/nginx_proxy_example.adoc
  modules/ROOT/partials/deployment/services/env-and-yaml.adoc
  modules/ROOT/partials/deployment/systemd.adoc
  modules/ROOT/partials/multi-location/event-bus.adoc
  modules/ROOT/partials/multi-location/idm-https-reverse-proxy.adoc
  modules/ROOT/partials/nav.adoc
Labels: documentation

#1128 [7.1] [PR 1125] Remove all occurrences and references of binary installations
  modules/ROOT/pages/architecture/architecture.adoc
  modules/ROOT/pages/conf-examples/search/configure-search.adoc
  modules/ROOT/pages/depl-examples/bare-metal.adoc
  modules/ROOT/pages/depl-examples/minimal-bare-metal.adoc
  modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-prod.adoc
  modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc
  modules/ROOT/pages/deployment/general/general-info.adoc
  modules/ROOT/pages/deployment/general/ocis-init.adoc
  modules/ROOT/pages/deployment/index.adoc
  modules/ROOT/pages/deployment/services/env-var-note.adoc
  modules/ROOT/pages/deployment/services/env-vars-special-scope.adoc
  modules/ROOT/pages/deployment/services/registry.adoc
  modules/ROOT/pages/deployment/services/s-list/audit.adoc
  modules/ROOT/pages/deployment/services/s-list/collaboration.adoc
  modules/ROOT/pages/deployment/services/s-list/postprocessing.adoc
  modules/ROOT/pages/deployment/services/s-list/storage-users.adoc
  modules/ROOT/pages/deployment/services/s-list/thumbnails.adoc
  modules/ROOT/pages/deployment/storage/general-considerations.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/maintenance/b-r/backup.adoc
  modules/ROOT/pages/maintenance/b-r/restore.adoc
  modules/ROOT/pages/maintenance/commands/commands.adoc
  modules/ROOT/pages/maintenance/commands/rolling-back-and-forward.adoc
  modules/ROOT/pages/migration/upgrading_7.0.0_7.1.0.adoc
  modules/ROOT/pages/prerequisites/prerequisites.adoc
  modules/ROOT/pages/quickguide/quickguide.adoc
  modules/ROOT/partials/deployment/apache_80_example.adoc
  modules/ROOT/partials/deployment/apache_harden_ssl.adoc
  modules/ROOT/partials/deployment/apache_proxy_example.adoc
  modules/ROOT/partials/deployment/dependent_startup.adoc
  modules/ROOT/partials/deployment/nginx_80_example.adoc
  modules/ROOT/partials/deployment/nginx_harden_ssl.adoc
  modules/ROOT/partials/deployment/nginx_proxy_example.adoc
  modules/ROOT/partials/deployment/services/env-and-yaml.adoc
  modules/ROOT/partials/deployment/systemd.adoc
  modules/ROOT/partials/multi-location/event-bus.adoc
  modules/ROOT/partials/multi-location/idm-https-reverse-proxy.adoc
  modules/ROOT/partials/nav.adoc
Labels: backport
